export const stages = [
  {
    id: "ecust",
    years: "2021.09 — 2025.06",
    place: "ECUST",
    role: "智能制造工程本科",
    context: "通过机械设计、嵌入式、测量控制和人工智能课程建立工程基础。",
    question: "怎样从单点技术走向完整机器人系统？",
    work: ["Tennis.ai：完成从视觉数据标注到模型微调的基础链路", "Robocon：覆盖除机械建模外的主要机器人链路", "MDATS：完成从问题定义、模型与实验到论文写作的研究闭环"],
    ownership: "在 Robocon 中从 STM32 电控出发，逐步承担上下位机、感知、定位、规划、系统集成与团队技术领导。",
    transition: "完整机器人系统的实践建立了系统观，也促使我进一步关注研究方法与真实控制问题。",
    tone: "sage",
  },
  {
    id: "industry",
    years: "2024.07 — 2024.09",
    place: "Shanghai Wuji Technology",
    role: "Robotics Control Intern",
    context: "在真实研发环境中面对交互控制、传感反馈、多执行器通信和跨职能协作。",
    question: "控制方法进入真实硬件后，怎样兼顾稳定性与灵敏度？",
    work: ["高保真遥操作与多轴控制仿真", "阻抗 / 导纳控制与扭矩反馈", "Linux C++ 上位机与 CAN 多电机控制"],
    ownership: "参与早期灵巧手遥操作研发，完成控制仿真和系统调试，并针对不稳定现象调整控制结构。",
    transition: "这段经历把课程中的控制方法带入真实系统，也让我更重视硬件约束、实验验证和工程协作。",
    tone: "clay",
  },
  {
    id: "penn",
    years: "2025.09 — 2027.05（预计）",
    place: "University of Pennsylvania",
    role: "MEAM M.S. · Mechatronics & Robotics",
    context: "在高级动力学、机电系统、工程数学和操作系统训练中继续扩展机器人研究基础。",
    question: "如何让既有系统工程能力服务于 VLA 后训练研究？",
    work: ["MEAM 510 自主移动机器人", "CIS 548 PennOS", "当前研究兴趣：VLA 后训练"],
    ownership: "继续保持从硬件到软件的工程闭环，同时建立更严格的研究阅读、实验验证和技术表达方法。",
    transition: "目前聚焦 VLA 后训练，并继续积累可复现的研究工作与公开成果。",
    tone: "blue",
  },
] as const;
